# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toniebox.pb.freshness-check.fc-response.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-toniebox.pb.freshness-check.fc-response.proto\"\xad\x01\n\x1bTonieFreshnessCheckResponse\x12\x14\n\x0ctonie_marked\x18\x01 \x03(\x06\x12\x0e\n\x06\x66ield2\x18\x02 \x02(\x05\x12\x13\n\x0bmax_vol_spk\x18\x03 \x02(\x05\x12\x0f\n\x07slap_en\x18\x04 \x02(\x05\x12\x10\n\x08slap_dir\x18\x05 \x02(\x05\x12\x0e\n\x06\x66ield6\x18\x06 \x02(\x05\x12\x13\n\x0bmax_vol_hdp\x18\x07 \x02(\x05\x12\x0b\n\x03led\x18\x08 \x02(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toniebox.pb.freshness_check.fc_response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TONIEFRESHNESSCHECKRESPONSE']._serialized_start=50
  _globals['_TONIEFRESHNESSCHECKRESPONSE']._serialized_end=223
# @@protoc_insertion_point(module_scope)
