# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: toniebox.pb.freshness-check.fc-request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,toniebox.pb.freshness-check.fc-request.proto\"?\n\x1aTonieFreshnessCheckRequest\x12!\n\x0btonie_infos\x18\x01 \x03(\x0b\x32\x0c.TonieFCInfo\",\n\x0bTonieFCInfo\x12\x0b\n\x03uid\x18\x01 \x02(\x06\x12\x10\n\x08\x61udio_id\x18\x02 \x02(\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'toniebox.pb.freshness_check.fc_request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TONIEFRESHNESSCHECKREQUEST']._serialized_start=48
  _globals['_TONIEFRESHNESSCHECKREQUEST']._serialized_end=111
  _globals['_TONIEFCINFO']._serialized_start=113
  _globals['_TONIEFCINFO']._serialized_end=157
# @@protoc_insertion_point(module_scope)
